### ISSUE TITLE
Configuration documentation

### ISSUE THREAD

**Issue by colunira** [pPrecel/Kyma-Mila#1]
There is no documentation of how to configure your script to fit user needs. That could scare away new users from using your amazing script. Please consider adding it in your free time :)

**Comment by pPrecel** [comment]
This program have some other bugs, but in this case you can type "kiła" in console to print documentation. Please read this [page](https://github.com/pPrecel/Kyma-Mila) to get more informations.

**Comment by colunira** [comment]
Cool, thanks for information, best developer ever <3
