### ISSUE TITLE
Small typo in console certs

### ISSUE THREAD

**Issue by KarolJaksik** [pPrecel/Kyma-Mila#2]
https://github.com/pPrecel/Kyma-Mila/blob/5c1757d1779f92fdf48149129eaa7d002767d97f/ki%C5%82a.sh#L40
Should be `echo Console certs...`

**Comment by pPrecel** [comment]
Thanks! Problem solved. See [this link](https://github.com/pPrecel/Kyma-Mila/pull/3) for more informations.
